# Generated by Django 5.2.9 on 2025-12-09 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("ADD", "Addition"),
                            ("SUB", "Subtraction"),
                            ("MUL", "Multiplication"),
                            ("DIV", "Division"),
                            ("PCT", "Percentage"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "difficulty_level",
                    models.IntegerField(
                        choices=[
                            (1, "Multiply by 11 (2 digits)"),
                            (2, "Multiply by 11 (3 digits)"),
                            (3, "Square numbers ending in 5"),
                            (4, "Multiply numbers close to 100"),
                            (5, "Multiply 2-digit numbers"),
                            (6, "Multiply 3-digit by 1-digit"),
                            (7, "Multiply 3-digit by 2-digit"),
                            (8, "Multiply 4-digit numbers"),
                            (9, "Division (exact)"),
                            (10, "Division (with decimals)"),
                            (11, "Percentages"),
                            (12, "Addition (multi-digit)"),
                            (13, "Subtraction (multi-digit)"),
                        ],
                        default=1,
                    ),
                ),
                ("operand1", models.DecimalField(decimal_places=10, max_digits=20)),
                ("operand2", models.DecimalField(decimal_places=10, max_digits=20)),
                (
                    "correct_answer",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                ("question_text", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_answer", models.DecimalField(decimal_places=10, max_digits=20)),
                ("is_correct", models.BooleanField()),
                ("time_taken_ms", models.IntegerField(blank=True, null=True)),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="trainer.question",
                    ),
                ),
            ],
        ),
    ]
