# Generated by Django 6.0 on 2025-12-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty_level',
            field=models.IntegerField(choices=[(14, 'Add/Subtract (below 50)'), (15, 'Multiply (factors ≤ 10)'), (16, 'Add/Subtract (below 100)'), (17, 'Multiply (up to 100 × 5)'), (18, 'Multiply (up to 100 × 10)'), (19, 'Negative numbers'), (20, 'Division (basic facts)'), (1, 'Multiply by 11 (2 digits)'), (2, 'Multiply by 11 (3 digits)'), (3, 'Square numbers ending in 5'), (4, 'Multiply numbers close to 100'), (5, 'Multiply 2-digit numbers'), (6, 'Multiply 3-digit by 1-digit'), (7, 'Multiply 3-digit by 2-digit'), (8, 'Multiply 4-digit numbers'), (9, 'Division (exact)'), (10, 'Division (with decimals)'), (11, 'Percentages'), (12, 'Addition (multi-digit)'), (13, 'Subtraction (multi-digit)')], default=1),
        ),
    ]
