# Generated by Django 5.2.9 on 2025-12-30 12:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainer", "0003_create_default_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeitnerCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("ADD", "Addition"),
                            ("SUB", "Subtraction"),
                            ("MUL", "Multiplication"),
                            ("DIV", "Division"),
                            ("PCT", "Percentage"),
                        ],
                        max_length=3,
                    ),
                ),
                ("operand1", models.DecimalField(decimal_places=10, max_digits=20)),
                ("operand2", models.DecimalField(decimal_places=10, max_digits=20)),
                (
                    "correct_answer",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                ("question_text", models.CharField(max_length=200)),
                (
                    "difficulty_level",
                    models.IntegerField(
                        choices=[
                            (1, "Multiply by 11 (2 digits)"),
                            (2, "Multiply by 11 (3 digits)"),
                            (3, "Square numbers ending in 5"),
                            (4, "Multiply numbers close to 100"),
                            (5, "Multiply 2-digit numbers"),
                            (6, "Multiply 3-digit by 1-digit"),
                            (7, "Multiply 3-digit by 2-digit"),
                            (8, "Multiply 4-digit numbers"),
                            (9, "Division (exact)"),
                            (10, "Division (with decimals)"),
                            (11, "Percentages"),
                            (12, "Addition (multi-digit)"),
                            (13, "Subtraction (multi-digit)"),
                        ],
                        default=1,
                    ),
                ),
                ("box_number", models.IntegerField(default=1)),
                (
                    "next_review",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_reviewed", models.DateTimeField(blank=True, null=True)),
                ("times_correct", models.IntegerField(default=0)),
                ("times_incorrect", models.IntegerField(default=0)),
                ("consecutive_correct", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leitner_cards",
                        to="trainer.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["next_review", "box_number"],
                "unique_together": {("user", "operation", "operand1", "operand2")},
            },
        ),
    ]
